using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Andy.Auth.Server.Tests.Configuration;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.WebUtilities;

namespace Andy.Auth.Server.Tests;

/// <summary>
/// Independent Production application hosts share real protected bundles, ring and
/// database. TestServer transports HTTP without a TLS handshake; network ingress
/// isolation is a separate #174 acceptance concern.
/// </summary>
public sealed class ProductionReplicaKeyAcceptanceTests
{
    private const string Issuer = "https://auth.replica.test/";
    private const string Password = "ReplicaAcceptance123!";
    private const string Callback = "http://localhost:4200/auth/callback";

    [Fact]
    public async Task ReplicasRotateAndRecover_WithoutLosingCookiesTokensOrRefreshGrants()
    {
        var root = Path.Combine(Path.GetTempPath(), "andy-replica-keys-" + Guid.NewGuid().ToString("N"));
        var original = Path.Combine(root, "original");
        var backup = Path.Combine(root, "backup");
        var restored = Path.Combine(root, "restored");
        var fixture = new ProductionKeyFixture(Path.Combine(original, "keys"));
        var cookies = new CookieContainer();
        string originalToken;
        string refresh;
        string firstKid;
        try
        {
            // Both instances publish identical keys. Antiforgery generated by A
            // is accepted by B; the resulting actual Identity cookie works on A.
            using (var first = Factory(original, fixture.Values))
            using (var a = Client(first))
            {
                using var second = Factory(original, fixture.Values);
                using var b = Client(second);
                Assert.Equal(await Kids(a), await Kids(b));
                await Login(a, b, cookies);
                using var session = await Send(a, cookies, HttpMethod.Get, "/Session");
                Assert.Equal(HttpStatusCode.OK, session.StatusCode);
                var issued = await AuthorizeAndExchange(a, b, cookies);
                originalToken = issued.Access;
                firstKid = new JsonWebToken(originalToken).Kid;
                await AssertSessionTruth(b, originalToken);
                // Exercise refresh between replicas before retaining the next
                // old-key refresh grant for the rolling key change.
                var refreshed = await Refresh(a, issued.Refresh);
                refresh = refreshed.Refresh;
            }

            fixture.Add("OpenIddict:Certificates:Signing:1", "signing-next",
                DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddDays(60));
            fixture.Add("OpenIddict:Certificates:Encryption:1", "encryption-next",
                DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddDays(60));
            fixture.Values["DataProtection:Certificates:1:Path"] = fixture.Values["DataProtection:Certificates:0:Path"];
            fixture.Values["DataProtection:Certificates:1:Password"] = ProductionKeyFixture.Password;
            fixture.Add("DataProtection:Certificates:0", "protection-next",
                DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddDays(60));

            // Separate future-key publication/selection tests cover preactivation.
            // These restarted hosts represent the overlap window after activation.
            using (var first = Factory(original, fixture.Values))
            using (var a = Client(first))
            {
                using var second = Factory(original, fixture.Values);
                using var b = Client(second);
                var kids = await Kids(a);
                Assert.Equal(kids, await Kids(b));
                Assert.Equal(2, kids.Length);
                Assert.Contains(firstKid, kids);
                await AssertSessionTruth(a, originalToken);
                await AssertSessionTruth(b, originalToken);
                using var oldCookie = await Send(b, cookies, HttpMethod.Get, "/Session");
                Assert.Equal(HttpStatusCode.OK, oldCookie.StatusCode);
                var renewed = await Refresh(b, refresh);
                Assert.NotEqual(firstKid, new JsonWebToken(renewed.Access).Kid);
                await AssertSessionTruth(a, renewed.Access);
                refresh = renewed.Refresh;
                // Generate a ring entry under the next wrapping certificate and
                // issue a new real cookie. Its protection must survive restore.
                first.Services.GetRequiredService<IKeyManager>().CreateNewKey(
                    DateTimeOffset.UtcNow.AddSeconds(-1), DateTimeOffset.UtcNow.AddDays(30));
            }

            var oldCookies = cookies;
            cookies = new CookieContainer();
            // Fresh hosts load the newly active ring entry instead of using an
            // already cached default key from before the wrapping-key rotation.
            using (var first = Factory(original, fixture.Values))
            using (var a = Client(first))
            {
                using var second = Factory(original, fixture.Values);
                using var b = Client(second);
                await Login(b, a, cookies);
                using var newCookie = await Send(b, cookies, HttpMethod.Get, "/Session");
                Assert.Equal(HttpStatusCode.OK, newCookie.StatusCode);
            }

            SqliteConnection.ClearAllPools();
            Copy(original, backup);
            Assert.Contains(Directory.GetFiles(Path.Combine(backup, "keys", "ring")),
                path => File.ReadAllText(path).Contains("encryptedSecret", StringComparison.Ordinal));
            Directory.Delete(original, recursive: true);
            Copy(backup, restored);
            var recovered = fixture.Values.ToDictionary(pair => pair.Key, pair =>
                pair.Value?.Replace(original, restored, StringComparison.Ordinal));
            using (var first = Factory(restored, recovered))
            using (var a = Client(first))
            {
                using var second = Factory(restored, recovered);
                using var b = Client(second);
                Assert.Equal(await Kids(a), await Kids(b));
                foreach (var replica in new[] { a, b })
                {
                    using var cookie = await Send(replica, cookies, HttpMethod.Get, "/Session");
                    Assert.Equal(HttpStatusCode.OK, cookie.StatusCode);
                    using var originalCookie = await Send(replica, oldCookies, HttpMethod.Get, "/Session");
                    Assert.Equal(HttpStatusCode.OK, originalCookie.StatusCode);
                    await AssertSessionTruth(replica, originalToken);
                }
                var afterRecovery = await Refresh(a, refresh);
                await AssertSessionTruth(b, afterRecovery.Access);
                Assert.NotEqual(firstKid, new JsonWebToken(afterRecovery.Access).Kid);
            }
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            if (Directory.Exists(root)) Directory.Delete(root, recursive: true);
        }
    }

    private static EnvironmentWebApplicationFactory Factory(string directory, Dictionary<string, string?> keys)
    {
        var values = keys.ToDictionary(pair => pair.Key.Replace(":", "__", StringComparison.Ordinal), pair => pair.Value);
        values["ADMIN_PASSWORD_DEFAULT"] = Password;
        return new EnvironmentWebApplicationFactory("Production", Path.Combine(directory, "auth.sqlite"), Issuer,
            extraEnvironment: values, provisionProductionKeys: false);
    }

    private static HttpClient Client(WebApplicationFactory<Program> factory) => factory.CreateClient(
        new WebApplicationFactoryClientOptions { BaseAddress = new Uri(Issuer), AllowAutoRedirect = false, HandleCookies = false });

    private static async Task<HttpResponseMessage> Send(HttpClient client, CookieContainer cookies,
        HttpMethod method, string path, HttpContent? content = null)
    {
        using var request = new HttpRequestMessage(method, path) { Content = content };
        request.Headers.TryAddWithoutValidation("Cookie", cookies.GetCookieHeader(new Uri(Issuer)));
        var response = await client.SendAsync(request);
        if (response.Headers.TryGetValues("Set-Cookie", out var values))
            foreach (var cookie in values) cookies.SetCookies(new Uri(Issuer), cookie);
        return response;
    }

    private static async Task Login(HttpClient formReplica, HttpClient loginReplica, CookieContainer cookies)
    {
        using var form = await Send(formReplica, cookies, HttpMethod.Get, "/Account/Login");
        var html = await form.Content.ReadAsStringAsync();
        var csrf = Regex.Match(html, "name=\"__RequestVerificationToken\"[^>]*value=\"([^\"]+)\"").Groups[1].Value;
        Assert.False(string.IsNullOrEmpty(csrf));
        using var login = await Send(loginReplica, cookies, HttpMethod.Post, "/Account/Login",
            new FormUrlEncodedContent(new Dictionary<string, string>
            {
                ["Email"] = "admin@andy-auth.local", ["Password"] = Password,
                ["__RequestVerificationToken"] = csrf
            }));
        Assert.Equal(HttpStatusCode.Redirect, login.StatusCode);
    }

    private static async Task<(string Access, string Refresh)> AuthorizeAndExchange(
        HttpClient authorizeReplica, HttpClient tokenReplica, CookieContainer cookies)
    {
        var verifier = Base64UrlEncoder.Encode(RandomNumberGenerator.GetBytes(32));
        using var authorize = await Send(authorizeReplica, cookies, HttpMethod.Get,
            QueryHelpers.AddQueryString("/connect/authorize", new Dictionary<string, string?>
            {
                ["client_id"] = "andy-docs-web", ["redirect_uri"] = Callback,
                ["response_type"] = "code", ["scope"] = "openid profile offline_access",
                ["code_challenge"] = Base64UrlEncoder.Encode(SHA256.HashData(Encoding.ASCII.GetBytes(verifier))),
                ["code_challenge_method"] = "S256"
            }));
        Assert.Equal(HttpStatusCode.Redirect, authorize.StatusCode);
        Assert.StartsWith(Callback, authorize.Headers.Location!.OriginalString);
        var code = QueryHelpers.ParseQuery(authorize.Headers.Location.Query)["code"].ToString();
        return await Tokens(tokenReplica, new Dictionary<string, string>
        {
            ["grant_type"] = "authorization_code", ["client_id"] = "andy-docs-web",
            ["redirect_uri"] = Callback, ["code_verifier"] = verifier, ["code"] = code
        });
    }

    private static Task<(string Access, string Refresh)> Refresh(HttpClient client, string token) => Tokens(client,
        new Dictionary<string, string> { ["grant_type"] = "refresh_token", ["client_id"] = "andy-docs-web", ["refresh_token"] = token });

    private static async Task<(string Access, string Refresh)> Tokens(HttpClient client, Dictionary<string, string> form)
    {
        using var response = await client.PostAsync("/connect/token", new FormUrlEncodedContent(form));
        Assert.True(response.IsSuccessStatusCode, await response.Content.ReadAsStringAsync());
        using var json = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        return (json.RootElement.GetProperty("access_token").GetString()!, json.RootElement.GetProperty("refresh_token").GetString()!);
    }

    private static async Task AssertSessionTruth(HttpClient client, string token)
    {
        using var request = new HttpRequestMessage(HttpMethod.Get, "/auth/session");
        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
        using var response = await client.SendAsync(request);
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        using var json = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        Assert.True(json.RootElement.GetProperty("authenticated").GetBoolean());
    }

    private static async Task<string[]> Kids(HttpClient client)
    {
        using var discovery = JsonDocument.Parse(await client.GetStringAsync("/.well-known/openid-configuration"));
        using var jwks = JsonDocument.Parse(await client.GetStringAsync(discovery.RootElement.GetProperty("jwks_uri").GetString()));
        return jwks.RootElement.GetProperty("keys").EnumerateArray().Select(key => key.GetProperty("kid").GetString()!)
            .OrderBy(kid => kid, StringComparer.Ordinal).ToArray();
    }

    private static void Copy(string source, string destination)
    {
        Directory.CreateDirectory(destination);
        foreach (var file in Directory.GetFiles(source)) File.Copy(file, Path.Combine(destination, Path.GetFileName(file)));
        foreach (var directory in Directory.GetDirectories(source)) Copy(directory, Path.Combine(destination, Path.GetFileName(directory)));
    }
}
